### ISSUE TITLE
Modbus

### ISSUE THREAD

**Issue by NailAgliev** [andvikt/mega_hacs#100]
Доброго времени суток!

Появилось необходимость управлять частотным преобразователем к которому подключена вентиляция. Управление только через Modbus RTU.

Было бы очень удобно сделать связку со [стандартной](https://www.home-assistant.io/integrations/modbus/#configuring-platform-fan) интеграцией.

Можно использовать rtuovertcp и указать localhost (hassio.local) для ip и порт на котором будет сервер пересылающий данные в мегу.

Возможно мега поддерживает функцию TCP/RTU шлюза но упоминание об этом я не нашел.

**Comment by andvikt** [comment]
Добрый день! Спасибо за идею, но боюсь я к ней вряд ли подступлюсь. Я все же делаю интеграцию в первую очередь для себя, а у меня модбаса нет и не предполагается. Но если есть желание реализовать - прошу добро пожаловать, pull request я с радостью приму
