### ISSUE TITLE
не получается изменить домен порта

### ISSUE THREAD

**Issue by unit76** [andvikt/mega_hacs#105]
пытаюсь изменить настройка порта меги в файле configuration.yaml

mega:
  mega1:
    22:
      name: "TEST"

(в данном случае пытаюсь изменить имя на TEST)

я уже перепробовал много вариантов, но не работает.
при каком условии применяются настройки?
я надеюсь не при удалении меги и добавления ее заново?
<img width="1028" alt="Снимок экрана 2022-03-28 в 20 10 00" src="https://user-images.githubusercontent.com/35662560/160451274-5159b311-0a29-4b41-99a1-180fe42a4b40.png">

Что я делаю не так?

**Comment by andvikt** [comment]
Названия меняются из интерфейса.

https://user-images.githubusercontent.com/39195436/160558877-91373ca0-e3d7-44f1-85ce-48335303cd54.mov

**Comment by unit76** [comment]
про название понятно,
а как домен поменять на определенных портах? 
У меня помимо света есть розетки, вентиляторы, контакторы, клапаны на воду, вход от терморегулятора в котле и откатные ворота и это все добро подключенно к выходам меги. 
Когда прошу Сири или Алису выключить свет, выключаются все выходы в том числе контактор (в роли мастера-выключателя) и обесточивается вообще весь дом

**Comment by andvikt** [comment]
> про название понятно, а как домен поменять на определенных портах? У меня помимо света есть розетки, вентиляторы, контакторы, клапаны на воду, вход от терморегулятора в котле и откатные ворота и это все добро подключенно к выходам меги. Когда прошу Сири или Алису выключить свет, выключаются все выходы в том числе контактор (в роли мастера-выключателя) и обесточивается вообще весь дом
> […](#)

Про домены - вы же читали документацию? ) https://andvikt.github.io/mega_hacs/yaml/
```yaml
mega:
  megaid1:
    10:
      domain: switch
```
Отмечу, что функция смены домена доступна только для ВЫХОДОВ с двумя состояниями вкл/выкл.

Но на самом деле вам не обязательно менять домен, вам нужно конфигурировать тип устройства средствами интеграции с Алисой/сири, обе интеграции позволяют делать это. вот по Алисе - https://github.com/dmitry-k/yandex_smart_home/blob/master/docs/advanced-settings.md#параметры-устройств-entity_config

вот по homekit - https://www.home-assistant.io/integrations/homekit/

Ваша проблема так же решается зонами/комнатами. С Алисой все делается из приложения яндекса в телефоне. Привяжите колонку к комнате и все устройства в этой комнате так же к той же комнате. Так команда выключи свет будет по-умолчанию выключать свет в той комнате в которой стоит колонка.
