### ISSUE TITLE
MegaD HomeAssistant integration не работает

### ISSUE THREAD

**Issue by GrigorovIN** [andvikt/mega_hacs#108]
**Описание**
После установки:
- MegaD в HACS;
- megad-proxy (version: v0.1.3) в Supervisor.
и добавления в 
mega: # название интеграции configuration.yaml
  allow_hosts:
    - 192.168.0.14
    - 192.168.0.68
    - 192.168.0.69
  megid:
    7:
      domain: switch
      invert: true
    8:
      domain: switch
      invert: true
Не добавляются автоматически порты. 
В моем понимании после установки должны появиться новые объекты, но их нет.
Что необходмо сделать, что бы интеграция MegaD заработала?

**Версии систем**
HA version: 
Версия core-2022.5.4
Тип установки Home Assistant Supervised
Home Assistant Supervisor
Операционная система хоста  Debian GNU/Linux 11 (bullseye)
Канал обновлений  stable
Версия supervisor-2022.05.1

mega_hacs version: v1.1.1
megad firmware version: 4.56b2
используется mqtt: true

**Ожидаемое поведение**
Прошу выложить более подробную инструкцию по установке.

**Screenshots**

**LOG**
can not find mdid=megid in []
06:45:20 – (ПРЕДУПРЕЖДЕНИЕ) mega (кастомная интеграция)
Updating command_line switch took longer than the scheduled update interval 0:00:02
06:39:39 – (ПРЕДУПРЕЖДЕНИЕ) Выключатель
Template warning: 'float' got invalid input 'unknown' when rendering template '{{ (states('sensor.motion_1_illuminance_lux') | float) | round(1)}}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2022.6
06:39:36 – (ПРЕДУПРЕЖДЕНИЕ) helpers/template.py - первое сообщение получено 06:39:36 и повторялось 2 раз
Configuration of the SQL sensor platform in YAML is deprecated and will be removed in Home Assistant 2022.6; Your existing configuration has been imported into the UI automatically and can be safely removed from your configuration.yaml file
06:39:31 – (ПРЕДУПРЕЖДЕНИЕ) SQL

**Comment by andvikt** [comment]
Вы следовали инструкции? https://andvikt.github.io/mega_hacs/settings/

Установка состоит из двух этапов: установка в HACS, затем стандартная установка в меню интеграций.
