### ISSUE TITLE
Работы с i2c датчиками, когда несколько устройств на порт

### ISSUE THREAD

**Issue by kamulchik** [andvikt/mega_hacs#11]
Здравствуйте!
Если на одном порту несколько i2c устройств, то датчик не подтягивается.
Что видно в HA: sensor.mega_24_style_input_select_margin

Enviroment: docker
HA version: 2021.2.3
mega_hacs version: v0.3.17a
megad firmware version: 4.44b9
используется mqtt: true

Описание правильного поведения
Получить тоже, что на одном датчике.
Если через curl, то можно получить так: /usr/bin/curl -X GET 'http://192.168.1.14/sec/?pt=24&scl=23&i2c_dev=bmx280&i2c_par=2'" - это влажность.

![Снимок экрана от 2021-02-11 20-49-51](https://user-images.githubusercontent.com/13658089/107677043-db096c00-6caa-11eb-8994-46ea83668321.png)
![Снимок экрана от 2021-02-11 20-50-24](https://user-images.githubusercontent.com/13658089/107677047-dc3a9900-6caa-11eb-9081-407755251749.png)

**Comment by andvikt** [comment]
что отвечает контроллер при запросе состояния порта по mqtt? и так же что отвечает при запросе по http: http://192.168.1.14/sec/?cmd=all

**Comment by kamulchik** [comment]
cmd=all:
OFF/6;OFF/16;OFF/24;OFF/21;OFF/177;OFF/35;OFF;OFF;OFF;OFF;0;ON;0;0;OFF;OFF;OFF;OFF;OFF;OFF;OFF;OFF/66;temp:23.62;OFF;;0;temp:32.06;temp:28.31;temp:31.50;OFF;;OFF;OFF/0;OFF;;OFF;195;OFF
По mqtt смотрю через explorer.. Ничего. Обновился до крайней прошивки, тоже ничего. Но если в настройках порта выбрать датчик, то всё ок. К интеграции видимо это отношения не имеет. Пойду на форум писать..

**Comment by kamulchik** [comment]
Да, Андрей это подтвердил...
_kamulchik, с этим ничего не сделаешь. Контроллер через параметр "Dev" должен точно знать, с чем он работает, так как адресация у шины I2C не уникальна.
Не всегда есть возможность использовать одну шину для разных устройств. И ваш пример это подтверждает.
SSD1306 и BME280 вообще нельзя в рамках MegaD-2561 использовать на одной линии SDA. SSD1306 требует инициализацию, а BME280 хранит в настройках порта калибровочные коэффициенты.
Если несколько устройств и могут висеть на одной шине вместе, то все показания пока можно считывать только по HTTP. В MQTT уходит только то, что указано в "Dev"._
