### ISSUE TITLE
Не отрабатывает одновременные команды на отключение портов (output)

### ISSUE THREAD

**Issue by YDenis1978** [andvikt/mega_hacs#111]
**Описание**
Получил баг на двух автоматизациях (на большем количестве не проверял), один триггер, одна физическая мегаД, два выхода. Срабатывает триггер, соответственно автоматизации тоже запускаются две одновременно. Но у одной выход срабатывает (вкл или выкл нагрузки), а у другой нет. Трассировка говорит что все Ок. Но если одну из двух автоматизаций отключить (та которая срабатывала Ок), то и вторая начинает корректно работать.

**Версии систем**
Enviroment: debian
HA version: 2022.7.3
mega_hacs version: v1.1.1
megad firmware version: fw: 4.55b9
используется mqtt: false

**Ожидаемое поведение**
Автоматизации с одним триггером на включение\выключение выходов, одна мегаД. Триггер срабатывает, одновременно выполняются все автоматизации, все выходы одновременно вкл\выкл.

**Screenshots**

**LOG**
Просьба прикладывать детальный лог, подробная инструкция как включать отладку по [ссылке](https://andvikt.github.io/mega_hacs/debug/)

**Comment by andvikt** [comment]
Попробуйте обновиться на новую версию, кажется проблема должна решиться
