### ISSUE TITLE
'NoneType' object has no attribute 'create_future'

### ISSUE THREAD

**Issue by MafiaUA** [andvikt/mega_hacs#112]
Все решилось. А хотя нет, все таки часть устройств не поддерживает группы новые. Пока разбираюсь какие.
Ха странно, если 1 обьект в группе - работает, добавляешь 2 работающих по 1 и сразу перестает.

**Comment by waitxd** [comment]
Проблема в `PriorityLock`. Он наследуется от `asyncio.Lock`, а начиная с Python 3.10 в нём больше не используется `loop`.
https://github.com/andvikt/mega_hacs/blob/d3f3eeedc52047a326b31ec0a76d56cc31785ae8/custom_components/mega/tools.py#L67
HomeAssistant с версии 2022.7 использует Python 3.10.
В качестве временного фикса замените `self._loop.create_future()` на `self._get_loop().create_future()`.
Но на самом деле вся структура PriorityLock требует пересмотра. В коде используется всего два варианта приоритетов (-1 и 0).

**Comment by andvikt** [comment]
> Проблема в `PriorityLock`. Он наследуется от `asyncio.Lock`, а начиная с Python 3.10 в нём больше не используется `loop`.
> 
> https://github.com/andvikt/mega_hacs/blob/d3f3eeedc52047a326b31ec0a76d56cc31785ae8/custom_components/mega/tools.py#L67
> 
> HomeAssistant с версии 2022.7 использует Python 3.10.
> 
> В качестве временного фикса замените `self._loop.create_future()` на `self._get_loop().create_future()`.
> 
> Но на самом деле вся структура PriorityLock требует пересмотра. В коде используется всего два варианта приоритетов (-1 и 0).

Спасибо за инфу, постараюсь в ближ дни исправить.

**Comment by MafiaUA** [comment]
> > Проблема в `PriorityLock`. Он наследуется от `asyncio.Lock`, а начиная с Python 3.10 в нём больше не используется `loop`.
> > https://github.com/andvikt/mega_hacs/blob/d3f3eeedc52047a326b31ec0a76d56cc31785ae8/custom_components/mega/tools.py#L67
> > 
> > HomeAssistant с версии 2022.7 использует Python 3.10.
> > В качестве временного фикса замените `self._loop.create_future()` на `self._get_loop().create_future()`.
> > Но на самом деле вся структура PriorityLock требует пересмотра. В коде используется всего два варианта приоритетов (-1 и 0).
> 
> Спасибо за инфу, постараюсь в ближ дни исправить.

Спасибо!

**Comment by xtiitx** [comment]
На свою голову обновил версию HA и сломал все автоматизации. Временный фикс вроде помог, но в журнал все равно сыпет ошибки. Ждем постоянного решения.

**Comment by InfernoFeniks** [comment]
Так же пришлось откатить версию HA до 2022.2.5, чтобы все продолжило работать. Замечено, что кроме ошибок в логе, работа системы Mega очень капризная на 2022.7.3

**Comment by andvikt** [comment]
Исправил, #113
