### ISSUE TITLE
Кастом портов

### ISSUE THREAD

**Issue by YDenis1978** [andvikt/mega_hacs#118]
Здравствуйте.
Подскажите пожалуйста. HAOS. Хочу кастомизировать порты меги.
Установлена интеграция меги. Так же в configuration.yaml прописал путь к интеграции (в отдельную папку):
mega: !include_dir_merge_list includes/mega
Код: 
s3:
    22:
      domain: switch
      invert: false

Стандартно релейный порт (выход) 22 конфигурируется как light, я же хочу чтоб был switch.
Все вышеперечисленное сделал, НА перегрузил, но никаких изменений не увидел.
Я что-то выполнил неверно?

благодарю

**Comment by Sheredeka** [comment]
Привет, думаю отвечу за автора примером своей конфигурации:

mega:
############################## Моноблок
  mega1:
    filter_values: [85] #фильтрую ошибочные показания от датчиков температуры
    24: #Теплый пол кухонный балкон
      domain: switch
    25: #Теплый пол Туалет
      domain: switch
    26: #Теплый пол Ванна
      domain: switch
    27: #Задвижка Холодная вода
      domain: switch
    28: #Задвижка Горячая вода
      domain: switch
    8: #Вентиляция в кабинете
      domain: switch
    10: #Вентиляция в Ванной
      domain: switch
    led:
      mega1_29_led: #Лента в детской
        ws28xx: true
        port: 29
        order: brg
        smooth: 1
        chip: 138
    39: #MegaD-16I-XT сигнальный провод INT
      skip: true
    19: #счетчик импульсов со счетчика электроэнергии
      skip: true
    42: #1wire датчики
      318495f0013c:
        device_class: temperature
      da8403000000:
        device_class: temperature
############################### MegaD-16I-XT Входы
    43e00: #Гиркон Туалет
      invert: true
    43e01: #Гиркон Ванна
      invert: true
    43e02: #Гиркон Кабинет
      invert: true
    43e03: #Движение Ванна
      invert: true
    43e04: #Движение Туалет
      invert: true
    43e05: #Гиркон Спальня
      invert: true
    43e12: #Движение кухня
      invert: true
############################### MegaD-16R-XT Реле
    40e04: #Вентилятор в туалете
      domain: switch
  mega2:
    7: #Движение Кабинет
      invert: true
