### ISSUE TITLE
версия 2022.9 не работает

### ISSUE THREAD

**Issue by amgstone** [andvikt/mega_hacs#122]
**Описание**
интеграция перестала работать после обновления на 2022.9

Unable to prepare setup for platform mega.light: Platform not found (cannot import name 'SUPPORT_WHITE_VALUE' from 'homeassistant.components.light' (/usr/src/homeassistant/homeassistant/components/light/__init__.py))

**Версии систем**
Enviroment: raspberry/linux/windows/macos/docker
HA version: 
mega_hacs version:
megad firmware version:
используется mqtt: true/false

**Ожидаемое поведение**
Описание правильного поведения

**Screenshots**

**LOG**
Просьба прикладывать детальный лог, подробная инструкция как включать отладку по [ссылке](https://andvikt.github.io/mega_hacs/debug/)

Logger: homeassistant.setup
Source: setup.py:320
First occurred: 21:07:00 (4 occurrences)
Last logged: 21:07:00

Unable to prepare setup for platform mega.light: Platform not found (cannot import name 'SUPPORT_WHITE_VALUE' from 'homeassistant.components.light' (/usr/src/homeassistant/homeassistant/components/light/__init__.py))

**Comment by znack14** [comment]
вот причина
https://developers.home-assistant.io/blog/2022/08/18/light_white_value_removed/

**Comment by amgstone** [comment]
а как поправить интеграцию?

**Comment by andvikt** [comment]
Спасибо! Поправлю сегодня

**Comment by invine** [comment]
убрал упоминание SUPPORT_WHITE_VALUE, у меня это поправило интеграцию

**Comment by OlegBON1** [comment]
> убрал упоминание SUPPORT_WHITE_VALUE, у меня это поправило интеграцию

Аналогично коллега)
