### ISSUE TITLE
Управление LED-лентой перестало работать с приходом обновления v1.1.4

### ISSUE THREAD

**Issue by Sheredeka** [andvikt/mega_hacs#127]
**Описание**
Управление LED-лентой перестало работать с приходом обновления 2022.9.4
При включении/выключении/изменении яркости или цвета вылетает ошибка, при этом управление лентой невозможно.

**Версии систем**
Enviroment: linux / HAOS
Home Assistant 2022.9.4
Supervisor 2022.08.6
Operating System 9.0
Frontend 20220907.2 - latest
mega_hacs version: v1.1.4
megad firmware version:  MegaD-2561 by ab-log.ru (fw: 4.55b7)
используется mqtt: false

**Ожидаемое поведение**
Восстановление работоспособности

**LOG**
```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/mega/light.py:207
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 00:11:47 (1 occurrences)
Last logged: 00:11:47

[140474767872672] list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 676, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 931, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 713, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 544, in async_handle_light_off_service
    await light.async_turn_off(**filter_turn_off_params(light, params))
  File "/config/custom_components/mega/light.py", line 238, in async_turn_off
    _before = self.get_rgbw()
  File "/config/custom_components/mega/light.py", line 206, in get_rgbw
    rgb = [
  File "/config/custom_components/mega/light.py", line 207, in <listcomp>
    round(x * self.max_values[i]) for i, x in enumerate(rgb)
IndexError: list index out of range

```

**CONFIG**
```
    led:
      mega1_29_led: #Лента в детской
        ws28xx: true
        port: 29
        order: brg
        smooth: 1
        chip: 138
```

**Comment by Sheredeka** [comment]
Откатился, оказывается ошибка появилась при переходе на версию mega_hacs version: v1.1.4.,
Даже на Home Assistant 2022.8.6 / Supervisor 2022.08.6 / Operating System 8.4 использование mega_hacs version: v1.1.4 не позволяет управлять LED-лентой.

**Comment by astranexus** [comment]
У меня та же проблема. 
  MD3:
    led:
      led_g:
        ports: [25, 27, 28]
        smooth: 1
        range: [20, 200]

[139839349356192] list index out of range
[139838736822768] list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 676, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 931, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 713, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 544, in async_handle_light_off_service
    await light.async_turn_off(**filter_turn_off_params(light, params))
  File "/config/custom_components/mega/light.py", line 238, in async_turn_off
    _before = self.get_rgbw()
  File "/config/custom_components/mega/light.py", line 206, in get_rgbw
    rgb = [
  File "/config/custom_components/mega/light.py", line 207, in <listcomp>
    round(x * self.max_values[i]) for i, x in enumerate(rgb)
IndexError: list index out of range

**Comment by Sheredeka** [comment]
Отлично! Лента теперь включается и выключается, так же регулируется яркость.
Вот только не меняет цвет RGB-лента.....

**Comment by Sheredeka** [comment]
Настройка порта с лентой в аддоне:
```
mega:
  mega1:
    led:
      mega1_29_led: #Лента в детской
        ws28xx: true
        port: 29
        order: brg
        smooth: 1
        chip: 138

```
Включил debug, попытался из панели разработчика отправить параметры на ленту:
Смотрим лог по порту:  ➜  ~ tail -f /config/home-assistant.log | grep "pt=29"

**Включение ленты:**

```
DEBUG (MainThread) [custom_components.mega.mega1] request: http://192.168.50.41/sec/?pt=29&chip=138&ws=000000
DEBUG (MainThread) [custom_components.mega.mega1] request: http://192.168.50.41/sec/?pt=29&chip=138&ws=000000
DEBUG (MainThread) [custom_components.mega.mega1] request: http://192.168.50.41/sec/?pt=29&chip=138&ws=181818
DEBUG (MainThread) [custom_components.mega.mega1] request: http://192.168.50.41/sec/?pt=29&chip=138&ws=1A1A1A
```

**Увеличение яркости до 100%:**
```
DEBUG (MainThread) [custom_components.mega.mega1] request: http://192.168.50.41/sec/?pt=29&chip=138&ws=343434
DEBUG (MainThread) [custom_components.mega.mega1] request: http://192.168.50.41/sec/?pt=29&chip=138&ws=4F4F4F
DEBUG (MainThread) [custom_components.mega.mega1] request: http://192.168.50.41/sec/?pt=29&chip=138&ws=696968
DEBUG (MainThread) [custom_components.mega.mega1] request: http://192.168.50.41/sec/?pt=29&chip=138&ws=828282
DEBUG (MainThread) [custom_components.mega.mega1] request: http://192.168.50.41/sec/?pt=29&chip=138&ws=9A9A9A
DEBUG (MainThread) [custom_components.mega.mega1] request: http://192.168.50.41/sec/?pt=29&chip=138&ws=B4B4B3
DEBUG (MainThread) [custom_components.mega.mega1] request: http://192.168.50.41/sec/?pt=29&chip=138&ws=CDCDCD
DEBUG (MainThread) [custom_components.mega.mega1] request: http://192.168.50.41/sec/?pt=29&chip=138&ws=E6E6E6
DEBUG (MainThread) [custom_components.mega.mega1] request: http://192.168.50.41/sec/?pt=29&chip=138&ws=FFFFFF
```

**Изменение цвета:**
`DEBUG (MainThread) [custom_components.mega.mega1] request: http://192.168.50.41/sec/?pt=29&chip=138&ws=FFFFFF
`
**_То есть отправляется просто последнее значение яркости._**

**Уменьшаем яркость до 50%:**
```
DEBUG (MainThread) [custom_components.mega.mega1] request: http://192.168.50.41/sec/?pt=29&chip=138&ws=FFFFFF
DEBUG (MainThread) [custom_components.mega.mega1] request: http://192.168.50.41/sec/?pt=29&chip=138&ws=E4E4E4
DEBUG (MainThread) [custom_components.mega.mega1] request: http://192.168.50.41/sec/?pt=29&chip=138&ws=CACACA
DEBUG (MainThread) [custom_components.mega.mega1] request: http://192.168.50.41/sec/?pt=29&chip=138&ws=B1B1B1
DEBUG (MainThread) [custom_components.mega.mega1] request: http://192.168.50.41/sec/?pt=29&chip=138&ws=989898
DEBUG (MainThread) [custom_components.mega.mega1] request: http://192.168.50.41/sec/?pt=29&chip=138&ws=808080
```

**Снова пытаемся менять цвет:**
`DEBUG (MainThread) [custom_components.mega.mega1] request: http://192.168.50.41/sec/?pt=29&chip=138&ws=808080`
_**Опять отправляется только последнее значение**_ 

**Выключение ленты:**
```
DEBUG (MainThread) [custom_components.mega.mega1] request: http://192.168.50.41/sec/?pt=29&chip=138&ws=808080
DEBUG (MainThread) [custom_components.mega.mega1] request: http://192.168.50.41/sec/?pt=29&chip=138&ws=676767
DEBUG (MainThread) [custom_components.mega.mega1] request: http://192.168.50.41/sec/?pt=29&chip=138&ws=4D4D4E
DEBUG (MainThread) [custom_components.mega.mega1] request: http://192.168.50.41/sec/?pt=29&chip=138&ws=343434
DEBUG (MainThread) [custom_components.mega.mega1] request: http://192.168.50.41/sec/?pt=29&chip=138&ws=1A1A1A
DEBUG (MainThread) [custom_components.mega.mega1] request: http://192.168.50.41/sec/?pt=29&chip=138&ws=010101
DEBUG (MainThread) [custom_components.mega.mega1] request: http://192.168.50.41/sec/?pt=29&chip=138&ws=000000
```
### Ощущение, что НА не понимает, что лента может менять цвет и отправляет в нее только яркость...

**Comment by andvikt** [comment]
> mega1_29_led

а если выключить  smooth?

**Comment by Sheredeka** [comment]
Закоментил #smooth - такое же поведение ((

**Comment by andvikt** [comment]
попробуйте v1.1.8b0

**Comment by Sheredeka** [comment]
Отлично! Цвет меняется как и яркость цвета... вот только конфиг "order: brg" не применяется, цвета перепутаны: выбирая синий - светит зеленым, красный - синим, зеленый - красным.
Истина где-то рядом 👌

**Comment by andvikt** [comment]
> Отлично! Цвет меняется как и яркость цвета... вот только конфиг "order: brg" не применяется, цвета перепутаны: выбирая синий - светит зеленым, красный - синим, зеленый - красным.
> Истина где-то рядом 👌

пробуйте 1.1.8b1

**Comment by Sheredeka** [comment]
Работает! но есть нюанс:
Тапаешь на синий - светится синим как положено, но поинтер (кружочек) указателя цвета ставится на красный в интерфейсе HA.
На всякий случай картинка... чтоб понятно было о чем я...
![image](https://github.com/andvikt/mega_hacs/assets/59475072/914b63b4-2b02-4c5b-8559-b2207f41572d)

**Comment by andvikt** [comment]
> Работает! но есть нюанс:
> Тапаешь на синий - светится синим как положено, но поинтер (кружочек) указателя цвета ставится на красный в интерфейсе HA.
> На всякий случай картинка... чтоб понятно было о чем я...
> ![image](https://user-images.githubusercontent.com/59475072/274189740-914b63b4-2b02-4c5b-8559-b2207f41572d.png)

пробуйте 1.1.8b2

**Comment by Sheredeka** [comment]
Отлично. Все работает как надо. Есть не критичное поведение яркости:
Ставим яркость 50%, затем тапаем на синий - загорается синим, поинтер на синем, яркость увеличивается до 64, далее тапаем на зеленый - все переключается но яркость уже 100%.
Пользоваться особо не мешает, но явно где-то баг сидит...
Видео прицепил.
[resizeRGB-ha.zip](https://github.com/andvikt/mega_hacs/files/12867197/resizeRGB-ha.zip)

**Comment by andvikt** [comment]
> Отлично. Все работает как надо. Есть не критичное поведение яркости:
> Ставим яркость 50%, затем тапаем на синий - загорается синим, поинтер на синем, яркость увеличивается до 64, далее тапаем на зеленый - все переключается но яркость уже 100%.
> Пользоваться особо не мешает, но явно где-то баг сидит...
> Видео прицепил.
> [resizeRGB-ha.zip](https://github.com/andvikt/mega_hacs/files/12867197/resizeRGB-ha.zip)

Пробуйте v1.1.8b3

**Comment by Sheredeka** [comment]
Ничего не поменялось, поведение осталось прежним.
