### ISSUE TITLE
Перестало получать данные с датчиков i2c

### ISSUE THREAD

**Issue by DeniMGL** [andvikt/mega_hacs#13]
**Описание**
Описание проблемы
После последней обновы все накрылось)

**Версии систем**
Enviroment: docker
HA version: core-2021.2.3
mega_hacs version: v0.4.1b18
megad firmware version: 4.49b3
используется mqtt: true

**Ожидаемое поведение**
Получал данные с датчиков, до вчерашней обновы все работало)

**Screenshots**

**LOG**
DEBUG (SyncWorker_7) [custom_components.mega.megad] process incomming message: Message(topic='megad/31', payload=b'{"port":31,"value":{"temp":22.70, "hum":39.90}}', qos=0, retain=0, subscribed_topic='megad/+', timestamp=datetime.datetime(2021, 2, 18, 9, 34, 4, 596839, tzinfo=datetime.timezone.utc))

**Comment by andvikt** [comment]
вроде нашел проблему, пробуйте
v0.4.1b19

**Comment by DeniMGL** [comment]
все гуд, спасибо!
