### ISSUE TITLE
Применение allow_hosts не очень понятно

### ISSUE THREAD

**Issue by Seva44** [andvikt/mega_hacs#132]
**Описание**
В каких случаях нужно использовать allow_hosts или это обязательное требование?
И какой ip адрес нужно указывать в этой настройке? Хоста или MegaD?
Заранее спасибо!

**Comment by andvikt** [comment]
в документации есть описание. эту настройку в целом трогать не нужно, нужно только если вы хотите потестирвоать поведение шаблона ответа от интеграции, подробно описано тут: https://andvikt.github.io/mega_hacs/http/#http-response
