### ISSUE TITLE
Зависает на "Подождите, запускается мастер настройки mega"

### ISSUE THREAD

**Issue by m637ex** [andvikt/mega_hacs#134]
**Описание**
На OrangePi зависает на "Подождите, запускается мастер настройки mega"
Иногда пишет после этого Unknown error
На VM VirtualBox Home assistent core Работало сразу.

**Версии систем**
Enviroment: Orange Pi PC Plus - armbian 22.08.8 Jammy with Linux 5.15.74-sunxi
HA version:  2022.11.4
mega_hacs version: 1.28.4
megad firmware version: 4.59b
используется mqtt: false

**Ожидаемое поведение**
Добавление контроллера

**Screenshots**
[https://disk.yandex.ru/i/3MwOMR2FjRnGTQ](url)

**LOG**
Logger: frontend.js.latest.202211080
Source: components/system_log/__init__.py:256
First occurred: 19:46:16 (3 occurrences)
Last logged: 19:46:21

:0:0 ResizeObserver loop completed with undelivered notifications. 
Просьба прикладывать детальный лог, подробная инструкция как включать отладку по [ссылке](https://andvikt.github.io/mega_hacs/debug/)

**Comment by m637ex** [comment]
ошибка - https://disk.yandex.ru/i/FU-XREqxIfrtVw

**Comment by andvikt** [comment]
не вижу проблем с интеграцией, проблема очевидно на стороне HA, больше ни от кого таких проблем не поступало
