### ISSUE TITLE
Автор забросил дополнение?

### ISSUE THREAD

**Issue by Dasisfakt** [andvikt/mega_hacs#135]
**Описание**
Описание проблемы

**Версии систем**
Enviroment: raspberry/linux/windows/macos/docker
HA version: 
mega_hacs version:
megad firmware version:
используется mqtt: true/false

**Ожидаемое поведение**
Описание правильного поведения

**Screenshots**

**LOG**
Просьба прикладывать детальный лог, подробная инструкция как включать отладку по [ссылке](https://andvikt.github.io/mega_hacs/debug/)

**Comment by andvikt** [comment]
Не забросил ) но времени на улучшения сейчас нет. Критичные баги правлю, тк сам пользуюсь

**Comment by Dasisfakt** [comment]
Фух, спасибо вам за труды. А то начал переживать, что в один прекрасный момент при обновлении все крякнет. Надеюсь время появится и баги будут устраняться. Кто пользуется дополнением задонатьте автору, для моральной поддержки. Ссылка находиться в hacs в карточке дополнения

**Comment by Sheredeka** [comment]
> ..... Кто пользуется дополнением задонатьте автору, для моральной поддержки. Ссылка находиться в hacs в карточке дополнения....

В ветке [форума ](https://www.ab-log.ru/forum/viewtopic.php?f=1&t=1788&start=680#p49297) идею с донатами чет не особо поддержали.... Умные дома видимо только у нищебродов....

**Comment by Sheredeka** [comment]
> Не забросил ) но времени на улучшения сейчас нет. Критичные баги правлю, тк сам пользуюсь

Давайте я отправлю вам через Андрея (ab-log.ru) LED-ленту WS2811 5M Black или White? - Вы установите ее себе, увидите баг, и прправете его выпустив новую версию)
А я обновлюсь уже наконец то с 2022.8.6.

andvikt - Организовываем?
