### ISSUE TITLE
Возможно, некорректность в логике фильтрации значений датчиков через filter_scale

### ISSUE THREAD

**Issue by pavelplus** [andvikt/mega_hacs#137]
В методе filter_value класса FilterBadValues участок кода
`abs(value - self._prev_value) / self._prev_value > self.filter_scale`
...всегда будет false при отрицательных значениях _prev_value (отрицательный знаменатель и abs числитель). Возможно, корректнее будет включить все выражение в abs:
`abs((value - self._prev_value) / self._prev_value) > self.filter_scale`

Также предвижу проблемы при переходе через ноль: когда _prev_value близко к нулю даже "нормальное" изменение value будет выходить за filter_scale (например, для растущей температуры: _prev_value = 0.1, value = 0.5, изменение всего на 0,4 градуса, а значение выражения будет (0,4-0,1)/0,1 = 3 (300%). При дальнейшем росте температуры алгоритм будет отбрасывать все последующие измерения как некорректные? Быстрое гугление по этому вопросу посылает куда-то в сторону фильтра Калмана или альфа-бета фильтра, но там все значительно усложняется за счет обработки нескольких предыдущих значений и предсказания "корректности" ожидаемого значения датчика...

Извиняюсь, если не разобрался в работе алгоритма - выбирал способ для отбрасывания периодических выбросов явных аномалий в показаниях уличного датчика, очень обрадовался, что автор предусмотрел эту функциональность в аддоне, зашел посмотреть на логику работы.

**Comment by andvikt** [comment]
Согласен с вами, этот фильтр изначально использовался для датчика углекислого газа, где значения были на уровне 500-1000, на самом деле я бы этот фильтр убрал-больше проблем чем пользы от него.

**Comment by andvikt** [comment]
исправлено в v1.1.8b6
