### ISSUE TITLE
Error while setting allowed hosts

### ISSUE THREAD

**Issue by Sheredeka** [andvikt/mega_hacs#140]
**Описание**
Ошибка в журнале после чистой установки на чистый НА

**Версии систем**
Home Assistant 2023.1.2
Supervisor 2022.12.1
Operating System 9.4
Frontend 20230104.0 - latest
используется mqtt: false

**LOG**
Logger: custom_components.mega.config_flow.mega3
Source: custom_components/mega/hub.py:164
Integration: mega ([documentation](https://github.com/andvikt/mega_hacs), [issues](https://github.com/andvikt/mega_hacs/issues))
First occurred: 10:46:28 (1 occurrences)
Last logged: 10:46:28

while setting allowed hosts
Traceback (most recent call last):
  File "/config/custom_components/mega/hub.py", line 164, in __init__
    hass.data[DOMAIN][CONF_HTTP].protected = protected
KeyError: 'mega'

**Comment by andvikt** [comment]
- исправлено в 1.1.8b6
