### ISSUE TITLE
while parsing value

### ISSUE THREAD

**Issue by abcdeyka** [andvikt/mega_hacs#142]
при использовании кастомной модификациипоявляеться while parsing value
Traceback (most recent call last):
  File "/config/custom_components/mega/sensor.py", line 121, in filter_value
    or (self.filter_low is not None and value < self.filter_low) \
TypeError: '<' not supported between instances of 'NoneType' and 'float'

**Comment by andvikt** [comment]
исправлено в 1.1.8b6
