### ISSUE TITLE
Как из события mega.get_port получить данные.

### ISSUE THREAD

**Issue by Seva44** [andvikt/mega_hacs#144]
**Описание**
Как из события mega.get_port получить данные.

**Версии систем**
Enviroment: raspberry
HA version: 9.5
mega_hacs version: 1.1.4
megad firmware version:
используется mqtt: false

**Ожидаемое поведение**
Я думал, что сервис mega.get_port отдаст мне состояние порта, но этого не произошло

**Comment by andvikt** [comment]
mega.get_port - это сервис для принудительного обновления состояния порта или портов. Я бы сказал, что это ненужный сервис, т.к. все порты и так автоматически обновляются с заданным интервалом.

Но тем не менее, как и любой сервис в HA, он не возвращает никаких данных, вместо этого он запрашивает внеочередное обновление состояние порта или портов.
