### ISSUE TITLE
Не обновляются значения сенсоров

### ISSUE THREAD

**Issue by dbdmitriev** [andvikt/mega_hacs#148]
**Описание**
К меге подключен DHT22 на 38 порту,в HA автоматически создались 2 сенсора (температура и влажность). При вызове mega.get_port(38) не происходит обновление значений сенсоров. В логах видно, что пришло новое значение влажности (было 33, стало 34.7). Однако сенсоры влажности и температуры не обновляются.

**Версии систем**
Enviroment: raspberry/linux/windows/macos/docker
HA version: 2023.6.2
mega_hacs version: 1.1.4
megad firmware version:
используется mqtt: false

**Ожидаемое поведение**
Описание правильного поведения

**Screenshots**

**LOG**
:

2023-06-18 13:15:25.793 DEBUG (MainThread) [custom_components.mega.mega_1] get port 38
2023-06-18 13:15:25.793 DEBUG (MainThread) [custom_components.mega.mega_1] request: http://192.168.2.198/sec/?pt=38&cmd=get
2023-06-18 13:15:25.918 DEBUG (MainThread) [custom_components.mega.mega_1] response temp:26.30/hum:34.70
2023-06-18 13:15:25.918 DEBUG (MainThread) [custom_components.mega.mega_1] parsed: {'value': {'temp': '26.30', 'hum': '34.70'}}

**Comment by 3AXAPOB** [comment]
Поддерживаю, ситуация аналогичная

**Comment by dbdmitriev** [comment]
@andvikt есть огромная просьба пофиксить. Проблема в использовании DataUpdateCoordinator,но я не разобрался с наскока.

**Comment by dbdmitriev** [comment]
надо в вставить в в [метод ](https://github.com/andvikt/mega_hacs/blob/21697d83aeb8a67d00791b717305d371e39fbb72/custom_components/mega/__init__.py#L291) явный пуш для координатора

`hub.updater.async_set_updated_data(hub.values)`

**Comment by andvikt** [comment]
> надо в вставить в в [метод ](https://github.com/andvikt/mega_hacs/blob/21697d83aeb8a67d00791b717305d371e39fbb72/custom_components/mega/__init__.py#L291) явный пуш для координатора
> 
> `hub.updater.async_set_updated_data(hub.values)`

mega.get_port пофиксю, но есть вопрос - а зачем вы используете вообще этот сервис? какая цель? если цель - обновление сенсора, то он и так обновляется, периодичность обновлений всех сенсоров указывается в основных натсройках интеграции. и автоматическое обновление у вас так же не работает?

mega.get_port по сути ненужный сервис, он остался с ранних версий интеграции, когда не было автообновления.

**Comment by andvikt** [comment]
исправил, пробуйте v1.1.8b4, но еще раз напомню - это не рекомендованный способ обновлять значения сенсоров.

**Comment by dbdmitriev** [comment]
мой кейс использования вынужденный. На меге (2561 V3) висит порядка 10 датчиков AM2320 (работают как DHT22). Так вот, при обновлении всех входов/выходов (через запрос состояния всех портов) мега подвисает на секунду-полторы (проблема внутри самого контроллера, очевидно). В этот момент события от выключателей (настроены на click, чтобы проще двойное/длительное нажатие обрабатывать) приходят абы как и без нужных полей вроде бы поле click отсутствует), в итоге освещение не работает, пользоваться крайне неудобно (нажал на выключатель, а ничего не произошло). Когда отключил автообновление вообще, события от выключателей стали проходить нормально. Так вот, сейчас настроена автоматизация раз в 30 сек дергается вызов get_port для списка портов (по одному). Пока работает стабильно.

**Comment by dbdmitriev** [comment]
> исправил, пробуйте v1.1.8b4, но еще раз напомню - это не рекомендованный способ обновлять значения сенсоров.

проверю, отпишусь, спасибо

**Comment by andvikt** [comment]
> мой кейс использования вынужденный. На меге (2561 V3) висит порядка 10 датчиков AM2320 (работают как DHT22). Так вот, при обновлении всех входов/выходов (через запрос состояния всех портов) мега подвисает на секунду-полторы (проблема внутри самого контроллера, очевидно). В этот момент события от выключателей (настроены на click, чтобы проще двойное/длительное нажатие обрабатывать) приходят абы как и без нужных полей вроде бы поле click отсутствует), в итоге освещение не работает, пользоваться крайне неудобно (нажал на выключатель, а ничего не произошло). Когда отключил автообновление вообще, события от выключателей стали проходить нормально. Так вот, сейчас настроена автоматизация раз в 30 сек дергается вызов get_port для списка портов (по одному). Пока работает стабильно.

а вы с проблемой обращались к производителю? это звучит очень странно - мега подвисает из-за одного единственного запроса? ?cmd=all ? или все-таки моя интеграция что-то такое делает что все виснет?

**Comment by dbdmitriev** [comment]
@andvikt интеграция все делает верно, тут никаких проблем, проблема именно внутри контроллера.
вот [тут мое сообщение](https://www.ab-log.ru/forum/viewtopic.php?f=1&t=1505&p=50038#p50038) на форуме производителя

P.S. 
1.1.8b4 get port работает корректно, обновляются сенсоры. Может, сразу починим и [расширители](https://github.com/andvikt/mega_hacs/issues/160)? Хотел PR сделать, прав нет.

**Comment by andvikt** [comment]
> @andvikt интеграция все делает верно, тут никаких проблем, проблема именно внутри контроллера. вот [тут мое сообщение](https://www.ab-log.ru/forum/viewtopic.php?f=1&t=1505&p=50038#p50038) на форуме производителя
> 
> P.S. 1.1.8b4 get port работает корректно, обновляются сенсоры. Может, сразу починим и [расширители](https://github.com/andvikt/mega_hacs/issues/160)? Хотел PR сделать, прав нет.

права на pr есть у всех, нужно делать fork и pr делать из него, но что касается этого исправления - я сделал в 1.1.8b5
