### ISSUE TITLE
MQTT помечен как устаревший

### ISSUE THREAD

**Issue by avdeevsv91** [andvikt/mega_hacs#15]
А можно узнать что послужило причиной такого решения? Вроде как с ним нет проблем и работает хорошо, есть не просит)

**Comment by andvikt** [comment]
) есть очень просит - любое изменение в интеграции просит вносить изменения и тут и там.
Протоколы разные от слова совсем.

Изначально я не до конца знал о всех http возможностях контроллера, а сейчас оказывается, что он так же как и по mqtt извещает сервер об абсолютно любых изменениях, поэтому не вижу смысл продолжать поддерживать mqtt, http лучше во всем - он быстрее, он полностью покрывает все функции контроллера, автор контроллера mqtt поддерживает неохотно

**Comment by avdeevsv91** [comment]
Очень жаль. Придется оставаться на старых версиях.

**Comment by andvikt** [comment]
Это конечно ваше право, но я не очень понимаю вашу мотивацию. 

http лучше и вы не потеряете в функционале вообще нисколько, а только приобретете. Для перехода нужно только нажать галку в интерфейсе и в меге поменять адрес и тип )

Тем не менее, я не буду сию минуту удалять mqtt и не буду удалять до тех пор пока он не начнет реально мешать. Может так получится, что не понадобится удаление вовсе. Но новых функций в нем скорее всего точно не будет.

**Comment by avdeevsv91** [comment]
>> Это конечно ваше право, но я не очень понимаю вашу мотивацию.

Издержки архитектуры доступа извне. Нет белого IP, брокер настроен в режиме моста к серверу во внешнем мире. Соответственно, все девайсы общаются по MQTT. Если переходить на HTTP, то придется писать автоматизации для эмуляции MQTT запросов, чтобы текущая система продолжала работать.

**Comment by andvikt** [comment]
Не очень понимаю, у вас мега и сервер в разных сетях? И они общаются по mqtt? Очень интересный кейс )

А если все же они в одной сети, то я тогда не понимаю вашу проблему ) центр вашей автоматизации - это ha, ему все равно как ваши устройства общаются, хоть mqtt, хоть bluetooth хоть что угодно, ha для этого и нужен, чтобы все имеющиеся протоколы, транспорты и прочее объединить в общую систему.

Или у вас были написаны автоматизации, которые слушали mqtt события и теперь их не очень хочется переписывать на "правильные" события state?

У меня в ha и mega и зигби и zwave и блютус и еще ворох разных wifi и прочей радости и мне абсолютно все равно что у них там под капотом-mqtt или tcp или udp или еще какая проприетарная фигня

**Comment by avdeevsv91** [comment]
Нет, вы все поняли не так. Мега, один из mqtt брокеров и сервер ha в одной сети. В другой сети есть еще один брокер, который сконфигурирован в мост с первый (инициация соединения изнутри домашней сети - таким образом "пробиваем" мост во внешний мир при отсутствии белого ip). Если перевести мегу в http, то соответственно пропадет возможность мониторинга/управления с помощью этого внешнего брокера. 

Чтобы все осталось работать при такой системе, придется писать автоматизации, которые при переключении выходов меги будут отсылать сообщения в нужные топики, и наоборот - при определенных сообщениях в этих топиках переключать выходы меги. По сути получается такая себе прослойка mqtt <-> http

**Comment by andvikt** [comment]
Вы очень все усложняете, очень ) ваша архитектура изначально мягко говоря слабая. Я бы посоветовал решать ваши проблемы с отсутствием белого ip путем dynamic dns. В ha есть суперудобный аддон на эту тему duck dns. У вас появится и внешний доступ по домену и ssl-шифрование и возможность ставить алису (если планировали), тк алиса не заведётся без домена и ssl

А сейчас вы придумали велосипед с квадратными колесами )

И самое главное опять же, центром должен быть ha, а не брокер. mqtt-это всего лишь протокол передачи сообщений, только и всего, как wifi, только гораздо менее функциональный )

**Comment by avdeevsv91** [comment]
И как dynamic dns поможет пробить nat?

**Comment by andvikt** [comment]
Вы пробовали? Ладно, я не вижу смысла продолжать эту дискуссию. По итогу: mqtt никто у вас не забирает ) нравится на квадратных колесах ездить-вперед.

**Comment by avdeevsv91** [comment]
> Вы пробовали?
Это технически невозможно. DynDNS помогает только в том случае, если у вас есть ДИНАМИЧЕСКИЙ БЕЛЫЙ IP (но нет статического). Если же сеть провайдера сидит за NAT'ом, то такая система просто не будет работать.

> mqtt никто у вас не забирает
Это хорошо. Меня просто смутила подпись, что в последствии MQTT будет полностью удален.

> нравится на квадратных колесах ездить-вперед
На данный момент ничего более лучшего я не нашел. Из вариантов остается только VPN туннель на внешний сервер или Home Assistant Cloud. Но что за первый, что за второй, придется ежемесячно платить. Тогда уж проще подключить услугу статического белого IP адреса. Но у меня цель именно в отсутствии дополнительных расходов на содержание УД.

**Comment by andvikt** [comment]
Ясно ) 

Но все равно неясно как это связано с мегой. Мега шлет свои состояния в ha ) то что она это делала через брокера, а теперь будет делать напрямую-какое это имеет отношение к вашей ситуации?)

Если вам нужно все стейты из ха направлять в брокера, вот вам наводка: https://www.home-assistant.io/integrations/mqtt_statestream/

И еще есть eventstream, двумя этими интеграциями люди объединяют несколько ha в одну сеть по mqtt

**Comment by avdeevsv91** [comment]
Благодарю за наводку, вот это действительно в данной ситуации поможет все реализовать более правильно!
