### ISSUE TITLE
Критическая ошибка после обновления на версию 2023.8.0

### ISSUE THREAD

**Issue by Dasisfakt** [andvikt/mega_hacs#151]
**Описание**
После обновления HA на версию 2023.8.0 MegaD перестала быть доступна, вернее объекты интеграции стали недоступны. Предполагаю, что многие столкнуться с этой проблемой...
Возможно это связано с новым принципом именования объектов

**Версии систем**
Enviroment: raspberry/linux/windows/macos/docker
HA version: 
mega_hacs version:
megad firmware version:
используется mqtt: true/false

**Ожидаемое поведение**
Описание правильного поведения

**Screenshots**

**LOG**

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:619
Integration: Сенсор (documentation, issues)
First occurred: 01:41:12 (4 occurrences)
Last logged: 02:05:06

Error adding entities for domain sensor with platform mega
Error while setting up mega platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'config_entries'

**Comment by znack14** [comment]
такая же история. откатился

**Comment by CagoBHuK** [comment]
Подтверждаю, работать в 2023.8.0 перестала. Откатился на 2023.7.

**Comment by cheese202** [comment]
Действительно отвалилось

**Comment by andvikt** [comment]
Исправлено в v1.1.5
