### ISSUE TITLE
Ошибка распределения входов и выходов в версии HA 2023.8.0

### ISSUE THREAD

**Issue by Dasisfakt** [andvikt/mega_hacs#152]
**Описание**
В версии HA 2023.8.0 интеграция неверно распределяет входы и выходы MegaD. Например: у входов (тип реле) нет переключателя для управления. У входов (датчиков) такая же история. Но все объекты появились в неком новом объекте, который создался автоматически. Скриншоты приложил.

**Screenshots**
https://disk.yandex.ru/i/xH44YBW7GYuxEA
https://disk.yandex.ru/i/B4y3FdzOqtlf-g
https://disk.yandex.ru/i/eJKFXhDveNXLrg

**LOG**
Просьба прикладывать детальный лог, подробная инструкция как включать отладку по [ссылке](https://andvikt.github.io/mega_hacs/debug/)

**Comment by pavelplus** [comment]
Есть такая проблема... Все объекты попали в дополнительное новое устройство, названное по имени одного из объектов (на первый взгляд случайного - у меня три меги, закономерности не увидел). Старые автоматизации работают, редактировать и делать новые не получается.

**Comment by Dasisfakt** [comment]
@andvikt взгляни пожалуйста на проблему, ее можно отнести к критическим. Новые автоматизации не сделать

**Comment by andvikt** [comment]
попробуйте 1.1.6b0, нужно включить в hacs бета-версии, отпишитесь - помогло ли

**Comment by andvikt** [comment]
но в целом в ha почему-то кардинально поменялась идентификация устройств.

> попробуйте 1.1.6b0, нужно включить в hacs бета-версии, отпишитесь - помогло ли

а точнее 1.1.6b1

**Comment by Dasisfakt** [comment]
@andvikt Да частично помогло, в устройствах объекты управления вернулись. Но вновь созданный автоматически объект остался. Так же у других устройств написано, что они подключены через этот объект, хотя например устройство "розетка 1" подключена через другой вход на меге
![2023-08-15_14-37-45](https://github.com/andvikt/mega_hacs/assets/58634053/6436b6c1-822c-448a-a70e-e12ca3e80f00)
![2023-08-15_14-37-01](https://github.com/andvikt/mega_hacs/assets/58634053/77d18727-68bb-451e-804e-61abdfd94549)
![2023-08-15_14-39-16](https://github.com/andvikt/mega_hacs/assets/58634053/1a231d2e-7a83-427e-8956-1401991e6280)
