### ISSUE TITLE
Неверное наименование портов расширителей

### ISSUE THREAD

**Issue by dbdmitriev** [andvikt/mega_hacs#160]
**Описание**
Значения датчиков (бинарных сенсоров) от расширителей неверно инициализируются:
на порту 31 подключен расширитель со списком сенсоров(герконы). В конфигурации для датчиков выставлены значение invert: true
`mega:
  mega_1:
    31e00:
      invert: true
    31e01:
      invert: true
    31e02:
      invert: true
    31e03:
      invert: true
    31e04:
      invert: true
    31e05:
      invert: true
    31e06:
      invert: true
    31e07:
      invert: true
    31e08:
      invert: true
    31e09:
      invert: true
    31e10:
      invert: true
    31e11:
      invert: true
`

При начальной загрузке HA значения сенсоров с номерами от 0 до 9 всегда FALSE, но меняются, если происходит сработка датчика. Датчики с номерами от 10 и выше инициализируются корректно. Если в конфигурации использовать номера портов без 0 (например, 31e5), инициализируются верно, но после первой сработки датчика инвертирование прекращается.

в binary_sensor.async_setup_entry возвращаются номера с 0 (31e01, etc)

Если изменить [строку](https://github.com/andvikt/mega_hacs/blob/21697d83aeb8a67d00791b717305d371e39fbb72/custom_components/mega/hub.py#L480C27-L480C27) на 
`ret[f"{port}e{i:02}"] = x`
все работает корректно

**Версии систем**
Enviroment: raspberry/linux/windows/macos/docker
HA version: 
mega_hacs version:
megad firmware version:
используется mqtt: true/false

**Ожидаемое поведение**
Порты имеют верное значение при старте приложения

**Screenshots**

**LOG**

[mega_d_log.json](https://github.com/andvikt/mega_hacs/files/12894515/mega_d_log.json)

**Comment by andvikt** [comment]
> **Описание** Значения датчиков (бинарных сенсоров) от расширителей неверно инициализируются: на порту 31 подключен расширитель со списком сенсоров(герконы). В конфигурации для датчиков выставлены значение invert: true `mega: mega_1: 31e00: invert: true 31e01: invert: true 31e02: invert: true 31e03: invert: true 31e04: invert: true 31e05: invert: true 31e06: invert: true 31e07: invert: true 31e08: invert: true 31e09: invert: true 31e10: invert: true 31e11: invert: true `
> 
> При начальной загрузке HA значения сенсоров с номерами от 0 до 9 всегда FALSE, но меняются, если происходит сработка датчика. Датчики с номерами от 10 и выше инициализируются корректно. Если в конфигурации использовать номера портов без 0 (например, 31e5), инициализируются верно, но после первой сработки датчика инвертирование прекращается.
> 
> в binary_sensor.async_setup_entry возвращаются номера с 0 (31e01, etc)
> 
> Если изменить [строку](https://github.com/andvikt/mega_hacs/blob/21697d83aeb8a67d00791b717305d371e39fbb72/custom_components/mega/hub.py#L480C27-L480C27) на `ret[f"{port}e{i:02}"] = x` все работает корректно
> 
> **Версии систем** Enviroment: raspberry/linux/windows/macos/docker HA version: mega_hacs version: megad firmware version: используется mqtt: true/false
> 
> **Ожидаемое поведение** Порты имеют верное значение при старте приложения
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **LOG**
> 
> [mega_d_log.json](https://github.com/andvikt/mega_hacs/files/12894515/mega_d_log.json)

пробуйте v1.1.8b5

**Comment by dbdmitriev** [comment]
проверил, работает. Спасибо
