### ISSUE TITLE
не подписей в настройках интеграции

### ISSUE THREAD

**Issue by skyer** [andvikt/mega_hacs#2]
![image](https://user-images.githubusercontent.com/668611/104820619-29138700-5847-11eb-99ae-5c58ea9cc6ba.png)

В /config/integrations в mega options нет подписей к полям, как при первой настройке

**Comment by andvikt** [comment]
Проблема в том что интеграция на русском языке, на английском нет подписей. Как будет время сделаю английский ) первая строка-кол-во секунд между обновлениями датчиков, вторая строчка - номер порта, который периодически пингуется для определения статуса меги (онлайн/офлайн)
