### ISSUE TITLE
Значение датчиков

### ISSUE THREAD

**Issue by InfernoFeniks** [andvikt/mega_hacs#29]
**Описание**
На последних версиях интеграции заметил странное поведение датчиков
HTU21D и DS18B20 перевел на интеграцию и странные значения выдают графики из истории.
Остальные работают по command_line и с ними все нормально, как видно из скриншота.
Вроде в самом начале, как перешел на интеграцию, около недели назад, все было норм.

**Версии систем**
Enviroment: intel nuc docker
HA version: core-2021.2.3 Home Assistant OS 5.12
mega_hacs version: v0.5.4b13
megad firmware version: (fw: 4.49b6)
используется mqtt: false

**Ожидаемое поведение**
Описание правильного поведения

**Screenshots**
![image](https://user-images.githubusercontent.com/70452034/109546967-e72f5f00-7adb-11eb-9d6f-85d99991c1ff.png)

**LOG**
Нужен ли он. Не знаю какой и за какой период нужен.

**Comment by andvikt** [comment]
А странно что? Что есть иногда выбросы? Так это у вас скорее всего линия 1wire не идеальна, у меня такое сплошь и рядом, когда датчиков много, напряжения всем иногда не хватает и они выдают огромный минус. Если бы дело было в интеграции то они бы вообще не работали

**Comment by andvikt** [comment]
А в логе нужно искать warning или error

**Comment by InfernoFeniks** [comment]
Но тут у вас видимо интервал обновления 0 )
Точно!!! Забыл про это. Сейчас поставлю, завтра увижу. А выбросы были когда проблема была у нас с бетами, когда мега не могла добавиться

**Comment by InfernoFeniks** [comment]
Все гуд! Графики теперь правильные. 
Хотел уточнить.
Периодичность обновлений в секундах - ок
А галочка "Обновлять выходы (регулярно) - можешь объяснить?
![image](https://user-images.githubusercontent.com/70452034/109777523-e1896480-7c14-11eb-9c8b-f35f3974cd5d.png)

**Comment by andvikt** [comment]
> Все гуд! Графики теперь правильные.
> Хотел уточнить.
> Периодичность обновлений в секундах - ок
> А галочка "Обновлять выходы (регулярно) - можешь объяснить?
> ![image](https://user-images.githubusercontent.com/70452034/109777523-e1896480-7c14-11eb-9c8b-f35f3974cd5d.png)

Эта штука для режима mqtt актуальна. Там каждый порт запрашивается по отдельности, поэтому по умолчанию выходы не запрашиваются, чтобы сэкономить время, но некоторым пользователям это было нужно, поэтому я сделал галку. А для http это не актуально, тк там все порты запрашиваются одной командой и получается что при каждом обновлении датчиков автоматом так же обновляются и состояния выходов.
