### ISSUE TITLE
Перестала отображаться температура

### ISSUE THREAD

**Issue by 3AXAPOB** [andvikt/mega_hacs#33]
Компонент не получает данные с датчика ds18b20
В МегаД датчик сконфигурирован так:
Type: Dsen
Sen: 1W
До обновления на 1.0 и выше температура показывалась в ХА.

**Comment by andvikt** [comment]
Буду проверять, откатитесь пока назад

**Comment by andvikt** [comment]
В логе ошибок или ворнингов нет?

**Comment by 3AXAPOB** [comment]
> В логе ошибок или ворнингов нет?

Всё чисто

**Comment by kamulchik** [comment]
Тоже самое, подтверждаю.
По логам 2021-03-24 12:26:44 DEBUG (MainThread) [custom_components.mega.mega] [<Entity mega_22_temp: None>, <Entity mega_26_temp: None>, <Entity mega_27_temp: None>, <Entity mega_28_temp: None>]

**Comment by andvikt** [comment]
Ок, вечером поправлю.

**Comment by andvikt** [comment]
Поправил раньше ) 1.0.3

**Comment by kamulchik** [comment]
Да, заработало, спасибо.
