### ISSUE TITLE
Ошибка в парсинге и ссылке на Github/документацию

### ISSUE THREAD

**Issue by alidonet** [andvikt/mega_hacs#36]
Использую актуальную версию на сегодняшний день HA, интеграции MegaD и прошивки моноблоков.
Решил добавить интеграцию для моноблока версии 3.1 (45 портов).

В списке портов проблемы с парсингом. Из HA ссылка на документацию открывает страницу HA, а не эту на github.

Enviroment: debian/RPi-PoE
HA version: 2021.3.4
mega_hacs version: ?
megad firmware version: 3.50
используется mqtt: false

**Ожидаемое поведение**
Простое описание порта в списке устройств интеграции, корректная ссылка на этот репозиторий.

![MegaD00_port](https://user-images.githubusercontent.com/7659676/113611600-6bcf4900-9657-11eb-8da4-d365037aab52.png)

![MegaD_Docs](https://user-images.githubusercontent.com/7659676/113611606-6e31a300-9657-11eb-9f69-4bed04e6289a.gif)

**Comment by andvikt** [comment]
Спасибо за инфу. 

Не понял про новую версию моноблока. У моноблока вроде нет новой версии )
Или вы все-таки говорите про MegaD-2561-RTC-V3?
И прошивка у вас не 3.50 а 4.50b3

Тем не менее, из скриншота вижу, что проблема не с парсингом портов, а с парсингом версии прошивки меги. И судя по всему в новой версии прошивки нет пробела после версии прошивки - нужно поправить регулярное выражение, поправлю в сл версии, в целом на функционал это не должно влиять

По поводу ссылки поправлю.

**Comment by andvikt** [comment]
исправлено в v1.0.6b4

**Comment by alidonet** [comment]
Проблема с парсингом осталась (добавлял интеграцию с нуля). Версия интеграции v1.0.6b7.

**Comment by andvikt** [comment]
исправлено в v1.0.6b8

**Comment by alidonet** [comment]
Работает, спасибо.
