### ISSUE TITLE
Invalid config for [mega]: required key not provided @ data['mega'][<class 'str'>]. Got None.

### ISSUE THREAD

**Issue by Webmonit** [andvikt/mega_hacs#37]
**Описание**
При попытке создать кастомизацию в Configuration.yaml выскакивала ошибка при проверке с содержанием:
Invalid config for [mega]: required key not provided @ data['mega'][<class 'str'>]. Got None.
Поскольку имя меги в UI было задано числом, ошибку удалось обойти переименованием.

**Версии систем**
Enviroment: raspberry/linux/windows/macos/docker
HA version: 
mega_hacs version: v0.6.3
megad firmware version:
используется mqtt: true/false

**Ожидаемое поведение**
При смене имени с чилового значения на буквенно-числовое, проблема решилась

**Screenshots**

**LOG**
Invalid config for [mega]: required key not provided @ data['mega'][<class 'str'>]. Got None.

**Comment by andvikt** [comment]
Лично у меня ошибки такой нет. Попробовал поставить цифровой id, валидация успешна. Но по факту кастомизация не работает )
И я понимаю почему, но править пока наверно не буду - не то чтобы очень важная проблема а времени у меня мало - это хобби
Как будет время попробую исправить

**Comment by andvikt** [comment]
похоже я понял в чем проблема ) думаю, в ближ версии исправлю

**Comment by Webmonit** [comment]
> похоже я понял в чем проблема ) думаю, в ближ версии исправлю

Спасибо, а еще с поддержкой ADS1115 видели вопрос? И Еще у меня megad-updater 0.2.9 не устанавливается, хотя proxy установился. Создать отдельный Issue? В логах:
`Step 1/15 : FROM php:7-alpine
 ---> 91cefd5154f6
Step 2/15 : ARG BASHIO_VERSION=0.12.1
 ---> Using cache
 ---> 88eb5617b415
Step 3/15 : ARG MEGAD_SCRIPT_URL=http://ab-log.ru/files/File/megad-cfg/megad-cfg-2561.zip
 ---> Using cache
 ---> 657397f3d588
Step 4/15 : ENV LANG C.UTF-8
 ---> Using cache
 ---> 106846765853
Step 5/15 : RUN mkdir -p /usr/src/bashio     && apk add --no-cache bash jq     && curl -L -f -s "https://github.com/hassio-addons/bashio/archive/v${BASHIO_VERSION}.tar.gz"         | tar -xzf - --strip 1 -C /usr/src/bashio     && mv /usr/src/bashio/lib /usr/lib/bashio     && ln -s /usr/lib/bashio/bashio /usr/bin/bashio     && docker-php-ext-install sockets
 ---> Running in be17e99e0165
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: temporary error (try again later)

WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: temporary error (try again later)

ERROR: unable to select packages:

  bash (no such package):
    required by: world[bash]
  jq (no such package):
    required by: world[jq]
Removing intermediate container be17e99e0165

21-04-10 16:57:43 INFO (SyncWorker_1) [supervisor.docker.addon] Starting build for 50f4faee/armv7-addon-megad-updater:v0.2.9
21-04-10 16:57:47 ERROR (SyncWorker_1) [supervisor.docker.addon] Can't build 50f4faee/armv7-addon-megad-updater:v0.2.9: The command '/bin/sh -c mkdir -p /usr/src/bashio     && apk add --no-cache bash jq     && curl -L -f -s "https://github.com/hassio-addons/bashio/archive/v${BASHIO_VERSION}.tar.gz"         | tar -xzf - --strip 1 -C /usr/src/bashio     && mv /usr/src/bashio/lib /usr/lib/bashio     && ln -s /usr/lib/bashio/bashio /usr/bin/bashio     && docker-php-ext-install sockets' returned a non-zero code: 2
21-04-10 16:57:47 ERROR (SyncWorker_1) [supervisor.docker.addon] Build log: 
Step 1/15 : FROM php:7-alpine
 ---> 91cefd5154f6
Step 2/15 : ARG BASHIO_VERSION=0.12.1
 ---> Using cache
 ---> 88eb5617b415
Step 3/15 : ARG MEGAD_SCRIPT_URL=http://ab-log.ru/files/File/megad-cfg/megad-cfg-2561.zip
 ---> Using cache
 ---> 657397f3d588
Step 4/15 : ENV LANG C.UTF-8
 ---> Using cache
 ---> 106846765853
Step 5/15 : RUN mkdir -p /usr/src/bashio     && apk add --no-cache bash jq     && curl -L -f -s "https://github.com/hassio-addons/bashio/archive/v${BASHIO_VERSION}.tar.gz"         | tar -xzf - --strip 1 -C /usr/src/bashio     && mv /usr/src/bashio/lib /usr/lib/bashio     && ln -s /usr/lib/bashio/bashio /usr/bin/bashio     && docker-php-ext-install sockets
 ---> Running in 31cffa190d5a
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: temporary error (try again later)

fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: temporary error (try again later)

ERROR: unable to select packages:

  bash (no such package):
    required by: world[bash]
  jq (no such package):
    required by: world[jq]
Removing intermediate container 31cffa190d5a`

**Comment by andvikt** [comment]
По апдейтеру лучше там завести issue

**Comment by andvikt** [comment]
исправил цифровые id меги в v1.0.6b4

**Comment by Webmonit** [comment]
Ух ты! У меня появились объекты как `ads1115_ch0` ! Очень круто!  Спасибо друг, с меня на пиво.
Только надо написать инструкцию, как попасть в обновление Beta_версий.

**Comment by andvikt** [comment]
> Ух ты! У меня появились объекты как `ads1115_ch0` ! Очень круто!  Спасибо друг, с меня на пиво.
> 
> Только надо написать инструкцию, как попасть в обновление Beta_версий.

Ну инструкция на самом деле есть ) в разделе установка. Просто инструкция уже довольно большая, логично, что не все и не все читают

**Comment by Webmonit** [comment]
Я читал, но там нет ни слова про переход на бета-версию.

**Comment by Webmonit** [comment]
Ну что? Я закрываю проблему?
