### ISSUE TITLE
1 wire

### ISSUE THREAD

**Issue by MihVSsochi** [andvikt/mega_hacs#44]
Здравствуйте, а как обнаружить датчики подключенные по шине 1-wire? У меня подключено 2 датчика температуры (dallas) на один порт по 1wbus, интеграция не видит их.

**Comment by andvikt** [comment]
Датчики должны определяться интеграцией. Как у вас настроен порт, на котором датчик? Приложите скриншот

**Comment by MihVSsochi** [comment]
Да, действительно стали определяться, у меня были проблемы с установкой интеграции, сейчас всё работает.
