### ISSUE TITLE
Диммеры

### ISSUE THREAD

**Issue by Lanfir7** [andvikt/mega_hacs#48]
Не пойму почему но не передается значение на уровень шим какой надо подавать при включении. Всегда использует последнее значение.
Вот пример моего скрипта

alias: Коридор
sequence:
- service: light.turn_on
data_template:
entity_id: light.37e15_koridor_steni
brightness_pct: 10

Я уже по разному пробовал, и просто data и через шаблоны запихивать.

**Comment by andvikt** [comment]
> Не пойму почему но не передается значение на уровень шим какой надо подавать при включении. Всегда использует последнее значение.
> Вот пример моего скрипта
> 
> alias: Коридор
> sequence:
> 
> * service: light.turn_on
>   data_template:
>   entity_id: light.37e15_koridor_steni
>   brightness_pct: 10
> 
> Я уже по разному пробовал, и просто data и через шаблоны запихивать.

Какая у вас версия, в логе есть ошибки?
Попробуйте включить дебаг, запустить сервис, что в логе?
Дебаг включается так: https://github.com/andvikt/mega_hacs/wiki/Отладка

**Comment by andvikt** [comment]
так, а вообще я вдумался в ваш вопрос - как вы включаете свет? если правилами на контроллере, а не в HA, то увы, то, что вы просите контроллер делать не умеет ни на расширителях, ни на стандартных выходах.

Но есть решение с использованием сервера, оно описано в моей документации: https://github.com/andvikt/mega_hacs/wiki/http

Обратите внимание на пример для порта номер 5

**Comment by andvikt** [comment]
Одно дополнение: пример в документации используется не для расширителя, а для стандартного выхода, но его легко адаптировать:

yaml
```
    5:
      # пример с использованием шаблона, порт 37 будет выключен если он сейчас включен и включен с последней сохраненной 
      # яркостью если он сейчас выключен   
      # яркость домножаем на 16, тк на расширителе разрядность в 16 раз больше
      response_template: >-
        {% if is_state('light.some_port_1', 'on') %}
        1:0
        {% else %}
        37e15:{{int(state_attr('light.some_port_1', 'brightness')) * 16}}
        {% endif %}
```

**Comment by Lanfir7** [comment]
Нет, мне надо средствами HA например в скрипте, у меня 8 обьектов (коридор) и там надо что бы днем включались они с одной яркостью а вечером с другой. Делаю как написал выше и у меня просто включается с последними данными. А задать яркость не могу. 
Делал через esp самодельное через мqnn и отлично работало. Решил вернуть через модуль новый для меня мега, что бы все красиво было и теперь не понимю как димирование сделать через скрипт

**Comment by Lanfir7** [comment]
Работает кстати если дублировать запись. То есть два раза просить включить с яркостью определенной. Типа первый раз с прошлыми настройками включает а потом меняет на правильные. Как это обойти, бред это. В других модулях работает же сразу.

**Comment by andvikt** [comment]
да, косяк вижу, пока не пойму в чем проблема, попробую исправить

**Comment by andvikt** [comment]
хотя нет, не воспроизводится, давайте лог все-таки, вот как у меня:
<img width="996" alt="Снимок экрана 2021-07-29 в 21 02 48" src="https://user-images.githubusercontent.com/39195436/127542669-316890b9-3878-4b24-b7a0-b4c1ebf9f6f5.png">

**Comment by andvikt** [comment]
сначала 0, потом сразу 82, никаких промежуточных 255 - все через сервис

**Comment by andvikt** [comment]
единственный случай, когда действительно происходит ваша ситуация - это если HA перезагружен и ваш свет в этот момент выключен. Тут уже точно надо подумать почему так )

**Comment by Lanfir7** [comment]
2021-07-29 21:15:54 DEBUG (MainThread) [custom_components.mega.mega] request: http://192.168.1.128/sec/?cmd=37e10:3264
2021-07-29 21:15:54 DEBUG (MainThread) [custom_components.mega.mega] response Done
2021-07-29 21:15:54 DEBUG (MainThread) [custom_components.mega.mega.mega_37e10] state is on

**Comment by andvikt** [comment]
и что это за лог? ) тут нет ничего интересного. Вобщем я разобрался, обнову выкачу сегодня

**Comment by Lanfir7** [comment]
Огромное спасибо! =) Ты большой молодец что сделал такой крутой модуль.

**Comment by andvikt** [comment]
Вам спасибо за внимание! ) важна обратная связь, я многим функционалом не пользуюсь, тк у меня мега вообще не про свет, поэтому сам не ловлю такие нюансы

**Comment by Lanfir7** [comment]
Еще нужна помощь, как бы сделать на 1 кнопку 1 скрипт и сруза на лонд, дабл, и обычное нажатие. А лучше вообще шаблон бы сделать, было бы очень круто

**Comment by andvikt** [comment]
обнова v1.0.8, жду обратной связи

**Comment by andvikt** [comment]
> Еще нужна помощь, как бы сделать на 1 кнопку 1 скрипт и сруза на лонд, дабл, и обычное нажатие. А лучше вообще шаблон бы сделать, было бы очень круто

кто же вам мешает сделать скрипт или шаблон? ) это уже кажется за рамками интеграции вопрос и тем более не в этом issue

**Comment by Lanfir7** [comment]
Бомба. Работает. Спасибо еще раз.
А шаблон, думал тебе проще сделать, и думаю многие скажут спасибо.

**Comment by andvikt** [comment]
> Бомба. Работает. Спасибо еще раз.
> А шаблон, думал тебе проще сделать, и думаю многие скажут спасибо.

я честно шаблонами не пользуюсь, ни разу не пробовал, так что понять что делать мне придется с нуля ) мне ближе python, поэтому активно использую для упаковки какой-то логики https://hacs-pyscript.readthedocs.io

Но это только на крайний случай ) когда yaml уже получается очень громоздкий, а так лучше хорошенько изучить встроенные возможности HA - они на самом деле большие и "правильные" архитектурно, те если делать автоматизации стандартными средствами - есть шанс что долго ничего не будет ломаться )
