### ISSUE TITLE
Устанавливать время на megad без RTC

### ISSUE THREAD

**Issue by lupin-de-mid** [andvikt/mega_hacs#56]
В документации сказно

"Достаточно отправить контроллеру запрос вида

**http://192.168.0.14/sec/?cf=7&stime=10:57:06:4**

Так как контроллер в момент своего включения отправляет на сервер сообщение с параметром "st=1", то сервер, получив это сообщение, может установить в контроллере правильное время."

Например  при включении меги  как указно в документации и раз в 5 минут все остальное время

**Comment by andvikt** [comment]
> В документации сказно
> 
> 
> 
> "Достаточно отправить контроллеру запрос вида
> 
> 
> 
> **http://192.168.0.14/sec/?cf=7&stime=10:57:06:4**
> 
> 
> 
> Так как контроллер в момент своего включения отправляет на сервер сообщение с параметром "st=1", то сервер, получив это сообщение, может установить в контроллере правильное время."
> 
> 
> 
> 
> 
> Например  при включении меги  как указно в документации и раз в 5 минут все остальное время

Эта функция реализована. В настройках интеграции (той что в интерфейсе) есть галка про время.

**Comment by lupin-de-mid** [comment]
Виноват, пропустил :(
