### ISSUE TITLE
Запрос статуса портов через mega.get_port

### ISSUE THREAD

**Issue by avdeevsv91** [andvikt/mega_hacs#6]
Если не указывать номера порта при вызове сервиса mega.get_port, то он запрашивает состояния всех портов, а не только тех, что присутствуют в списке устройств интеграции. Возможно, это так и задумано (хотя, если у меня их нет в интеграции, то зачем их опрашивать? они же отключены в настройках megad и/или с помощью опции skip в yaml).

Если это не ошибка, то хотелось бы либо иметь опцию в этом сервисе для пропуска исключенных портов (например skipped: true - запрашивать исключенные порты (по умолчанию для обратной совместимости); skipped: false - игнорировать исключенные порты), либо позволить указывать список (а не только один порт, как сейчас) нужных через параметр port.
```yaml
port:
  - 1
  - 2
  - 3
```

**Comment by andvikt** [comment]
Готово, [v0.3.13](https://github.com/andvikt/mega_hacs/releases/tag/v0.3.13)

Сделал и запрос нескольких портов и учет skipped

**Comment by avdeevsv91** [comment]
К сожалению, не работает:
```
[1752471032] unhashable type: 'list'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 136, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1455, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1490, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/mega/__init__.py", line 224, in _get_port
    await hub.get_port(port)
  File "/config/custom_components/mega/hub.py", line 257, in get_port
    async with self.notifiers[port]:
TypeError: unhashable type: 'list'
```

**Comment by andvikt** [comment]
> К сожалению, не работает:
> 
> ```
> [1752471032] unhashable type: 'list'
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 136, in handle_call_service
>     await hass.services.async_call(
>   File "/usr/src/homeassistant/homeassistant/core.py", line 1455, in async_call
>     task.result()
>   File "/usr/src/homeassistant/homeassistant/core.py", line 1490, in _execute_service
>     await handler.job.target(service_call)
>   File "/config/custom_components/mega/__init__.py", line 224, in _get_port
>     await hub.get_port(port)
>   File "/config/custom_components/mega/hub.py", line 257, in get_port
>     async with self.notifiers[port]:
> TypeError: unhashable type: 'list'
> ```

Исправил, версия v0.3.13a

**Comment by avdeevsv91** [comment]
Спасибо, теперь срабатывает! Однако, возник вопрос - если мониторить mqtt запросы при вызове службы mega.get_port, то видно что интеграция делает по три одинаковых запроса для каждого указанного порта (см. скриншот, было запрошено состояние порта 1). Это ошибка? Зачем запрашивать одно и то же значение три раза подряд?

![1](https://user-images.githubusercontent.com/16743879/107083612-f38b0980-6806-11eb-93b5-f595868cd727.png)

**Comment by andvikt** [comment]
Это странно. Интеграция ничего такого не делает. У вас случайно не 3 контроллера с одинаковыми id? id тот что в настройках контроллера указывается.

Еще вопрос-какой тип порта у вас на порту 1?

Попробуйте делать запрос с указанием id меги (id тот который вы придумали в настройках)

И кстати зачем вам впринципе этот сервис? Просто обновлять порты смысла нет, если вы используете mqtt и у вас последняя прошивка, то все само обновляется. Любые изменения на контроллере (даже если их делаете не вы, а контроллер по сценариям) обязательно отражаются в mqtt.

Обновлять датчики тоже не нужно, обновление датчиков делается автоматически в рамках интервала обновления.

Единственная ситуация, которую mqtt не ловит-это перезагрузка контроллера. После перезагрузки все состояния будут висеть на прежнем статусе, хотя по факту без сохранения все упадут в выкл. Но это нештатная ситуация.

Этот сервис я делал так, на всякий случай, тогда я еще не очень был уверен в надежности автоматических обновлений.

**Comment by avdeevsv91** [comment]
Контроллер в сети только один. Порт 1 настроен как OUT (реле на свет). Запрос с указанием id меги проходит хорошо (с одним пакетом). Поправлю этот момент у себя в автоматизациях, но тут явно какой то баг.
Службу get_port использую для предотвращения ситуаций после отключения электроэнергии, когда мега уже стартовала и состояние одного из портов изменилось, а сервер УД еще не загрузился. Согласен, отключение бывает редко, но все же бывает. Не критично, конечно, но если есть возможность это учесть, то почему бы и не воспользоваться.

P.S. Еще не понял как работать со skipped - в параметрах службы ничего нового не добавилось, а по умолчанию опрашиваются все порты, как и было до этого.

**Comment by andvikt** [comment]
> Контроллер в сети только один. Порт 1 настроен как OUT (реле на свет). Запрос с указанием id меги проходит хорошо (с одним пакетом). Поправлю этот момент у себя в автоматизациях, но тут явно какой то баг.
> 
> Службу get_port использую для предотвращения ситуаций после отключения электроэнергии, когда мега уже стартовала и состояние одного из портов изменилось, а сервер УД еще не загрузился. Согласен, отключение бывает редко, но все же бывает. Не критично, конечно, но если есть возможность это учесть, то почему бы и не воспользоваться.
> 
> 
> 
> P.S. Еще не понял как работать со skipped - в параметрах службы ничего нового не добавилось, а по умолчанию опрашиваются все порты, как и было до этого.

Если использовать флаг retain на самом контроллере, то во время отсутствия ha в сети, брокер все запомнит и передаст ha как только он подключится.

Тут только вопрос доступности брокера, если он стартует медленно, то да, сообщения потеряются.

Вообще вы меня натолкнули на мысль о том, что нужно во время сканирования сенсоров еще и выходы тоже сканировать. В след версии добавлю соответствующую функцию с возможностью включения в настройках.

По поводу skipped вообще если вы используете skipped в yaml, то должно работать тут автоматически, ничего в параметры передавать не нужно. Я правда не тестировал, но добавил соответствующие проверки во время сканирования. Но с другой стороны-ну просканирует он лишние порты и что с того? На пару десятков миллисекунд дольше будет это делать.

**Comment by andvikt** [comment]
Вобщем изменил немного логику. Skipped по сути роли теперь не играет, гет порт сканирует только те порты, которые впринципе были добавлены во время сканирования (на это так же влияет skip)

Исправил баг который приводил к нескольким сканированиям. 

И так же добавил опцию сканирования выходов во время общего сканирования всех портов. Нужно в настройках поставить соответствующую галку

**Comment by avdeevsv91** [comment]
Отлично работает. Спасибо!
