### ISSUE TITLE
Периодичность обновления

### ISSUE THREAD

**Issue by ruslantag** [andvikt/mega_hacs#67]
**Описание**
Добрый вечер
Подскажите, если поставлю периодичность обновления  1 сек,  это не даст сильную нагрузку на Mega?
Использую MegaD-2561, 77 портов используется

**Comment by andvikt** [comment]
1сек-очень часто, зачем вам так часто?

Я бы не рекомендовал чаще 5сек и то все равно практического смысла в этом мало, стандартно 30-60сек более чем достаточно. С таким частым обновлением растет не только нагрузка на мегу, самой-то меге в целом все равно, растет нагрузка на сеть и на ваш сервер, на бд. Каждый порт будет прочитан и записан в бд, записан лог об этом чтении и тд-это очень много скорее всего ненужной информации.

**Comment by ruslantag** [comment]
Настроил интеграцию, не работает датчик температуры SHT31.
В меге данные есть, в интеграции по одному датчику показывает все время температуру 130.
По второму  по нулям.

**Comment by andvikt** [comment]
> Настроил интеграцию, не работает датчик температуры SHT31.
> В меге данные есть, в интеграции по одному датчику показывает все время температуру 130.
> По второму по нулям.

Перенес в новый issue #72, пробелму вроде починил в v1.1.1b0, просьба протестирвоать, тк у меня нет этого датчика
