### ISSUE TITLE
Filter_low

### ISSUE THREAD

**Issue by Vittaly76** [andvikt/mega_hacs#73]
**Описание**
Пытаюсь воспользоваться Filter_low для значения сенсора (DS18B20). При проверке файла конфигурации HA выдаёт ошибку:

`Invalid config for [mega]: value must be at least 0 for dictionary value @ data['mega']['entities']['sensor.mega_06_temp']['filter_low']. Got -10.0`

**Версии систем**
Enviroment: linux debian 11
HA Supervised

HA version: 2021.10.7
mega_hacs version: 1.1.0
megad firmware version:
используется mqtt: false

**Ожидаемое поведение**
Описание правильного поведения

**Screenshots**

**LOG**
Просьба прикладывать детальный лог, подробная инструкция как включать отладку по [ссылке](https://andvikt.github.io/mega_hacs/debug/)

**Comment by andvikt** [comment]
Покажите, как вы записываете конфигурацию

**Comment by andvikt** [comment]
Да, действительно есть така проблема. Исправлю

**Comment by andvikt** [comment]
Исправил в v1.1.1b0, просьба проверить, что все равботает

**Comment by Vittaly76** [comment]
Да, ошибка ушла. Спасибо!

**Comment by Vittaly76** [comment]
Решено
