### ISSUE TITLE
Не обновляется состояние выходов

### ISSUE THREAD

**Issue by kasitoru** [andvikt/mega_hacs#89]
**Описание**
Есть вход, при срабатывании которого переключается состояние одного из выходов (настроено через act контроллера).
Проблема в том, что в HA состояние этого выхода не обновляется. Точнее обновляется только при запросе состояния всех портов, а не сразу после его изменения.

**Версии систем**
Enviroment: raspberry pi 4
HA version: 2021.11.5
mega_hacs version: 1.1.0
megad firmware version: 4.51b7
используется mqtt: false

**LOG**
В логах состояние отображается моментально сразу после срабатывания, но интеграция почему то этого не видит:
> 2021-11-21 23:52:07 DEBUG (MainThread) [custom_components.mega.http.http] request from ::1 <CIMultiDictProxy('X-Real-IP': '192.168.1.3', 'Host': 'localhost:8123', 'Connection': 'close', 'User-Agent': 'megad', 'Accept': 'text/html', 'Cache-Control': 'no-cache')>
2021-11-21 23:52:07 DEBUG (MainThread) [custom_components.mega.http.http] Request: {'pt': '18', 'cnt': '15', 'mdid': 'megad'} from '::1'
2021-11-21 23:52:07 DEBUG (MainThread) [custom_components.mega.http.http] response 
2021-11-21 23:52:07 DEBUG (MainThread) [custom_components.mega.http.http] request from 127.0.0.1 <CIMultiDictProxy('X-Real-IP': '192.168.1.3', 'Host': 'localhost:8123', 'Connection': 'close', 'User-Agent': 'megad', 'Accept': 'text/html', 'Cache-Control': 'no-cache')>
2021-11-21 23:52:07 DEBUG (MainThread) [custom_components.mega.http.http] Request: {'pt': '1', 'mdid': 'megad', 'v': '1'} from '127.0.0.1'

**Comment by kasitoru** [comment]
Решил попробовать откатиться на версию v1.0.9, там такой проблемы нет, все работает идеально!

**Comment by andvikt** [comment]
У вас эти порты в конфете не указаны c параметром skip: true?

**Comment by kasitoru** [comment]
Разумеется нет, иначе бы эти порты пропали из списка устройств интеграции.

**Comment by Vittaly76** [comment]
Присоединяюсь, аналогичная проблема на текущей версии аддона. Раньше такого не было. но с какой-то версии проблема появилась. Вроде бы чинится путём установки галки "Обновить все выходы когда срабатывает вход" в настройках интеграции. но это криво (как минимум дополнительно грузит контроллер лишними запросами, а также вносит задержку около 1 сек). При этом в документации на мегу сказано, что контроллер при изменении состояния выхода самостоятельно шлёт на сервер информацию: 

```
Если в системе используется сервер, он прописан в настройках, и порты контроллера переключались внутренней логикой: сценарий с признаком обязательного выполнения (Act с флажком), задания по расписанию (Cron), условное программирование (Program), контроллер отправляет на сервер сообщения об изменениях состояния входов

http://192.168.0.250/megad.php?pt=7&v=1
```

Было быц очень здОрово починить этот баг.

**Comment by znack14** [comment]
> Решил попробовать откатиться на версию v1.0.9, там такой проблемы нет, все работает идеально!

поставил эту версию - проблема осталась

**Comment by kasitoru** [comment]
Похоже, исправлено в [v1.1.1](https://github.com/andvikt/mega_hacs/releases/tag/v1.1.1). Спасибо!

**Comment by Vittaly76** [comment]
> Похоже, исправлено в [v1.1.1](https://github.com/andvikt/mega_hacs/releases/tag/v1.1.1). Спасибо!
Добрый день!
Да, точно помню - после этого вашего поста я у себя проверил на v1.1.1 - действительно, заработало. Но сейчас на той же версии опять не работает. Свяфзываю это с обновлением HA. У меня сейчас core-2021.12.6. И та же самая проблема...

**Comment by kasitoru** [comment]
`core-2021.12.8` - проблемы не наблюдаю, все работает хорошо.

**Comment by Vittaly76** [comment]
> `core-2021.12.8` - проблемы не наблюдаю, все работает хорошо.

Обноыился до 2021.12.8 - проблема осталась... А какая у вас версия прошивки меги? У меня 4.37b7

**Comment by kasitoru** [comment]
@Vittaly76 версия `4.51b7`

**Comment by Vittaly76** [comment]
> @Vittaly76 версия `4.51b7`

Попробую обновиться - возможно, дело в этом. Спасибо!

**Comment by Vittaly76** [comment]
Обновил онтроллер до `4.51b7` - всё заработало, как надо. Спасибо ещё раз!
