### ISSUE TITLE
Не подключается вторая Мега 

### ISSUE THREAD

**Issue by sankey-1** [andvikt/mega_hacs#90]
**Описание**
Имеется два контроллера Мега-D. До недавнего времени все работало стабильно, но после перезагрузки всех устройств по питанию (в том числе и сервера) не стартует второй контроллер, при этом идет ооооочень долгий запуск первого (ориентировочно мин 10) после чего первый стартует, а на втором появляется статус "не удалось настроить"

**Версии систем**
Enviroment: docker
HA version: core-2021.11.5
mega_hacs version: v1.1.0
megad firmware version: 4.54b4
используется mqtt: false

**Ожидаемое поведение**
Ранее при перезапуске НА все подымалось моментально. Бывали случае когда интеграция Мега не поднималась, если в момент запуска НА по тем или иным причинам контроллеры отваливались от сети, но при повторном перезапуске НА все восстанавливалась

**Screenshots**

**LOG**
Logger: homeassistant.config_entries
Source: custom_components/mega/hub.py:436 
Integration: mega (documentation, issues) 
First occurred: 08:59:46 (1 occurrences) 
Last logged: 08:59:46

Error setting up entry mega2 for mega
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/mega/__init__.py", line 202, in async_setup_entry
    hub: MegaD = await _add_mega(hass, entry)
  File "/config/custom_components/mega/__init__.py", line 194, in _add_mega
    if not await hub.authenticate():
  File "/config/custom_components/mega/hub.py", line 436, in authenticate
    async with aiohttp.request("get", url=f"http://{self.host}/{self.sec}") as req:
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1161, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 905, in start
    self._continue = None
  File "/usr/local/lib/python3.9/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

**Comment by andvikt** [comment]
Кажется, это не связано с интеграцией. Таймаут у вас изза того что не отвечает контроллер. Причем именно не отвечает, еслиб в сети его не было, то была бы другая ошибка. А тут уже вопрос, что там произошло у вас с питанием.

**Comment by andvikt** [comment]
Долгий старт происходит потому что они стартуют по очереди и пока все не заведутся, ha будет считать что вся интеграция не завелась. Одно из устройств не отвечает и интегиация долго и упорно пытается добиться ответа, в конце концов сваливается по таймауту. Попробуйте перепрошить контроллер, на котором таймаут

**Comment by sankey-1** [comment]
в итоге я перепрошил меги и все нормализовалось, но спустя некоторое время повторилось. После последней ошибки при запуске я поменял порт в настройках меги с 8124 на 8123, запустилось с первого раза. Буду наблюдать дальше
ЗЫ: проблема только с одной меной (моноблок). прошивки на обоих были одной версии
