### ISSUE TITLE
Не стартует интеграция.

### ISSUE THREAD

**Issue by Ihor-Ua** [andvikt/mega_hacs#93]
**Описание**
При запуске сервера не стартует интеграция mega с версией 1.1.0, после ручного рестарта все работает как положено. При откате на версию 1.0.9 все работает как положено.

**Версии систем**
docker
HA version:  2021.11.5
mega_hacs version: 
megad firmware version:
используется mqtt: true/false

**Ожидаемое поведение**
Описание правильного поведения

**Screenshots**

**LOG**
Просьба прикладывать детальный лог, подробная инструкция как включать отладку по [ссылке](https://andvikt.github.io/mega_hacs/debug/)

**Comment by andvikt** [comment]
Без лога разбираться не с чем.

**Comment by andvikt** [comment]
Я думаю, знаю в чем была проблема, ставьте 1.1.1
