### ISSUE TITLE
HTTPS на меге...

### ISSUE THREAD

**Issue by Tanzpol** [andvikt/mega_hacs#94]
Приветствую, активно в своих проектах использую Меги, и тут вчера меня попросили подключить Алису. Проблем нет, получил внешний адрес, сделал сертификаты, переключился на https, и тут отвалилась мега... осталось только обновление раз в 30 секунд,   переключить работу ha в режим локальной сети в http при работающем https снаружи, не получится, судя по документации, может через какие то адоны типо gnix это сделать можно, но все же, может можно доделать вашу замечательную Интеграцию, что бы она работала с https?

**Comment by andvikt** [comment]
> Приветствую, активно в своих проектах использую Меги, и тут вчера меня попросили подключить Алису. Проблем нет, получил внешний адрес, сделал сертификаты, переключился на https, и тут отвалилась мега... осталось только обновление раз в 30 секунд,   переключить работу ha в режим локальной сети в http при работающем https снаружи, не получится, судя по документации, может через какие то адоны типо gnix это сделать можно, но все же, может можно доделать вашу замечательную Интеграцию, что бы она работала с https?
> 
>  

С интеграцией проблем нет, проблема в меге, она не способна работать по https. Но решение есть: https://github.com/andvikt/mega_addon/tree/master/mega-proxy

**Comment by andvikt** [comment]
Там обратите внимание на последний пункт в документации аддона:

Если вы пользуетесь ssl и у вас не работает аддон, используйте порт 8125 в натсройках контроллера

**Comment by andvikt** [comment]
Но я если честно не рекомендую впринципе встроенные механизмы https в ha, гораздо удобнее пользоваться nginx, для этого есть аддон, уже входящий в comunity addons, называется ngunx proxy manager. Он использует cert bot для автоматической выдачи/обновления сертификатов, домены настраиваются просто как раз-два-три и с ним не будет никаких проблем с незащищенными подключениями в локальной сети. В локальной сети смысла в https нет никакого.

**Comment by Tanzpol** [comment]
Большое спасибо за ответ! Да с Документацией нашел 8125 порт уже после того, как написал вам сообщение, там работает все ок! С Gnix пошел разбираться! Еще раз спасибо! Интеграция отличная!
