### ISSUE TITLE
Не работает интеграция вообще.

### ISSUE THREAD

**Issue by Rainstation** [andvikt/mega_hacs#95]
**Описание**
Установил MegaD через HACS. Установил megad-updater и megad-proxy через подключаемый репозитарий. Установил интеграцию и прописал настройки ID меги, сохранил, ошибок нет, но и ничего не добавляется в систему.
Интеграция выглядит так:
![mega2](https://user-images.githubusercontent.com/57766559/146058704-e4a5a2a3-696a-4cbc-a355-c7e09720aeeb.png)
Т.е. ничего не добавляется.
В логах нет никаких ошибок связанных с интеграцией.
Пробовал убрать прокси и подключить напрямую мегу в интеграцию - картина не меняется. Обновил megad_hacs до беты 1.1.1b2 - не помогло. 
Приведу скриншоты некоторых настроек:

![mega](https://user-images.githubusercontent.com/57766559/146058931-0c6aa9c5-2d17-459f-a655-a1826f50bdd9.png)
![mega1](https://user-images.githubusercontent.com/57766559/146058948-afee20b4-0d29-4f1f-9e02-defe4c7d4896.png)
![ha1](https://user-images.githubusercontent.com/57766559/146058966-99f1e2b7-98b0-433e-80c1-7e9ccfb5292f.png)
![megaD-proxy](https://user-images.githubusercontent.com/57766559/146059007-1bf04310-e1b1-4662-9d84-1385feec48a8.png)

**Версии систем**
## System Health

version | core-2021.12.1
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.0-9-amd64
arch | x86_64
timezone | Europe/Moscow

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4897
Installed Version | 1.18.0
Stage | running
Available Repositories | 912
Installed Repositories | 11

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2021.12.1
docker_version | 20.10.9
disk_total | 115.9 GB
disk_used | 13.8 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.3), Node-RED (10.2.0), Terminal & SSH (9.2.1), ESPHome (2021.12.0), Portainer (2.0.0), Studio Code Server (3.7.0), InfluxDB (4.3.0), megad-proxy (v0.1.3), megad-updater (v0.3.3)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 2
views | 10
mode | storage

</details>
Enviroment: linux docker
HA version: 2021.12.1
mega_hacs version: 1.1.1b2
megad firmware version: MegaD-2561 by ab-log.ru (fw: 4.51b7)
используется mqtt: false (в меге)

**Ожидаемое поведение**
Интеграция заработает и появятся объекты (сенсоры, переключатели и т.п)

**Screenshots**
Привел выше
**LOG**
Не понял как включить лог, по ссылке инструкция не показывается(((

**Comment by andvikt** [comment]
Сейчас будет дурацкий вопрос: А у вас на самом контроллере порты настроены?)

По логу, который вы показали, вижу, что контроллер до прокси стучится.

Лог включается так: https://andvikt.github.io/mega_hacs/debug/

**Comment by Rainstation** [comment]
Вы уж меня простите пожалуйста)) Это не дурацкий вопрос, иногда))
Действительно, не сконфигурированы порты меги. Года полтора лежала, достал-включил, но забыл что надо конфигурировать порты.
Спасибо за пинок в правильном направлении.
