### ISSUE TITLE
Нужно больше типов устройств

### ISSUE THREAD

**Issue by unit76** [andvikt/mega_hacs#99]
Начиная с прошивки от 09.09.2021 ver 4.53 beta1 было добавлено поле Title для каждого входа.
![MegaD-2561-port-title](https://user-images.githubusercontent.com/35662560/150380849-a4aca567-e0df-4cd1-8c1c-924ba6db59a7.png)

Предлагаю использовать его для определения типа выхода и входа.
Например если поле начинается со специального знака % то: 
%B-button кнопка
%F-fan вентилятор
%G - garage door гаражные ворота (1 выход и 2 входа на крайние положение ворот не знаю как завести это в HA)
%L - light освещение
%O - outlet розетка
%T - температура
%H - humidity влажность
%M motion sensor датчик движения
%S smoke sensor датчик дыма
%W- water sensor датчик воды
%C- co2 sensor
...

так же можно и инвертирование распознавать например
если %MI то это датчик движения с инвертированием сигнала.

а то что дальше переносить в название в HA

**Comment by andvikt** [comment]
Поддержка этого поля только на новой версии самого контроллера. И мало в этом смысла, тк все это можно сделать в ha в конфигурации
